//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mercado.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class SuperContainer : DbContext
    {

        public const string ConnectionString = "name=SuperContainer";
        public const string ContainerName = "SuperContainer";


        public SuperContainer() : base("name=SuperContainer")
        {
        }

        public SuperContainer(string connectionString) : base(connectionString)
        {
        }


        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Empresa> Empresas { get; set; }
        public virtual DbSet<Local> Locales { get; set; }
        public virtual DbSet<Sector> Sectores { get; set; }
        public virtual DbSet<Articulo> Articulos { get; set; }
        public virtual DbSet<Venta> Ventas { get; set; }
    }
}
